### ISSUE TITLE
师傅有没有兴趣一起日龙猫

### ISSUE THREAD

**Issue by Dispa1r** [lixiang810/totoroschool#1]
rt

**Comment by lixiang810** [comment]
有有有，欢迎PR

**Comment by lixiang810** [comment]
讲道理我才大一，而且学的专业也与CS无关，搞这个只是个人兴趣。有劳CTF大佬赐教

**Comment by Dispa1r** [comment]
大一Tql，师傅方便加个联系方式吗，等我这周考完可以一起讨论，我看别的师傅整过类似的app，这种app太恶心人了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lixiang810/totoroschool"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月7日(星期一) 下午5:14
收件人:&nbsp;"lixiang810/totoroschool"<totoroschool@noreply.github.com&gt;;
抄送:&nbsp;"858689519"<858689519@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [lixiang810/totoroschool] 师傅有没有兴趣一起日龙猫 (#1)





 
讲道理我才大一，而且学的专业也与CS无关，搞这个只是个人兴趣。有劳CTF大佬赐教

**Comment by lixiang810** [comment]
有无telegram？不太想用WeCheck和QQ等墙内软件联系能用tg的人，我的技术圈子也主要在tg上

**Comment by FuckerLinda** [comment]
有一说一，龙猫校园确实a piece of shlt。要不是懂点门道，不知道还要白跑多少次

**Comment by lixiang810** [comment]
> 有一说一，龙猫校园确实a piece of shlt。要不是懂点门道，不知道还要白跑多少次

它后端没有sanitizing，可以sql注入。
（后果自负）
