### ISSUE TITLE
现在用模拟比如fake location是不是对龙猫没用了

### ISSUE THREAD

**Issue by VoxHwa** [lixiang810/totoroschool#3]
我之前发现可以改系统时间跑限定时间的阳光跑，现在貌似被修复了。
不知道模拟定位还能不能用，😂希望交流一下。
看了龙猫收的数据，还是只能说国内app能不用就不用，qqvx我也不想用。

**Comment by lixiang810** [comment]
模拟定位还能用。

**Comment by VoxHwa** [comment]
是用的vmos+Fake Location嘛，我这好几个人用fakelocation都说龙猫定位不会动，但导航软件会动

**Comment by lixiang810** [comment]
我是真机，有 root

**Comment by VoxHwa** [comment]
我试试

**Comment by VoxHwa** [comment]
貌似有的虚拟机可以有的虚拟机就不太行，我同学用的夜神可以阳光跑，龙猫还是反作弊机制不太行😂

**Comment by lixiang810** [comment]
> 我之前发现可以改系统时间跑限定时间的阳光跑，现在貌似被修复了。

这一点在前晚得到了确认。以前龙猫的时间限制是在客户端判定的，所以可以改时间绕过，而现在在服务端也判定了一次。
